### PR TITLE
Corrects dates of RubyConf Brasil

### PR DESCRIPTION
**Pull request by danzanzini**

### CODE REVIEW

**Comment by geraldb** [comment]
Note the CALENDAR.md page gets auto-generated (using the [eventdb gem/script](https://github.com/textkit/event.db)), please do NOT edit.  Please DO update/change the README.md page/entry. That's the "reai" one-and-only source. Thanks. Cheers.

**Comment by geraldb** [comment]
Ok. To make it easy I will update the README.md. Please update the README.md in the future. Thanks.

**Comment by geraldb** [comment]
Ok. Double checking the page it looks Aug/28+29 is the date of 2014 not for 2015. The date for 2015 needs to get confirmed? Do you have any information? Cheers.

**Comment by danzanzini** [comment]
@geraldb, sorry for the wrong PR. I noticed that later so I've closed it.

The date is correct, just the website that is not updated. They have a twitter account (https://twitter.com/rubyconfbr) with news from the 2015 edition.

**Comment by geraldb** [comment]
@danzanzini  Great. Thanks for the update. Cheers.

**Pull request closed without merging**
