### PR TITLE
Fix RubyConfMY <-> RubyConf Indonesia

### PR DESCRIPTION
**Pull request by palkan**

### CODE REVIEW

**Comment by geraldb** [comment]
Great catch. Thanks for the fixes and updates. 

Note: @palkan  If you're interested in helping from time-to-time in keeping the list update-to-date  you're more than welcome to join the planetruby org (if you're interested I  send you an invite for the org (via github) so you can edit /change the page "inline" without pull request etc.  Cheers. Keep it up.

**Comment by palkan** [comment]
Yep, I'd be glad to help!

**Comment by palkan** [comment]
Here I am. Thank you!

**Comment by geraldb** [comment]
Great. Welcome.  Note: You will get an invitation (by email from GitHub) to join the PlanetRuby org as a member. If you accept, you can update the events page in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/planetruby/people)).

**Comment by palkan** [comment]
Done!

**Pull request merged**
